let grains = [
'ask a friend or coworker what your strenghs and weaknesses are',
'ask a random person what their favorite song is, play it, then jam out to it with them',
'"ask someone who you kind of know what is their #1 hobby',
'ask somone to move to Mexico with you, dont smile for a few seconds and see what they say',
'call someone you love',
'change your posture, try standing or sit up straight',
'develop a cool secret handshake with the next person you see',
'do 5 push ups',
'do the hokey pokey and you turn yourself around',
'do your best celebrity impersonation',
'enjoy a walk in silence for a while',
'finish all your sentences with "in accordance with the prophecy"',
'give a warm hug to someone right now',
'give every person you come in contact with a compliment today',
'greet the next person you see in a different language ',
'laugh for no reason for 15 seconds',
'lay down on the ground and say "I got this" really loudly',
'learn a new word and use it five times today',
'leave a dollar bill in a public place and see what happens',
'lip sync for 30 seconds to a song your vibing with right now',
'listen to a song in a different langauge',
'maintain eye contact with a stranger ',
'only make left turns for 30 minutes, even while you walk',
'part your hair on the opposite side or rub your head',
'people watch for as long you can, see the beauty within every person who passes',
'pick an accent different than your own and speak in it for 30 minutes',
'press the button for a different floor in an elevator to where you work or where you are going, get off and meet people at a random new company or service, tell them what you are up to',
'put your watch on the opposite hand',
'read the last page in a book nearby',
'send a message to somone who you have not spoken to in a long time',
'sit down on a bench and strike up a conversation with the first person who walks by',
'skip instead of walk to your next destination',
'spend a few minutes looking at your own eyes in the mirror',
'spend five or ten minutes with yourself to reflect through prayer or meditation',
'stand up and walk around during your calls today',
'start break dancing the best you can for 30 seconds ',
'switch up placement of your rings or jewelry',
'take a photo of your barefeet on the grass or ground',
'take something apart and put it back together',
'take the stairs ',
'text someone who you forgot to reply to recently',
'walk backwards as long as you can without looking behind you',
'walk up to someone and ask them if they can complete this phrase "in west philadelphia born and raised"',
'when you withdraw money from the atm yell "i won i won! third time this week!"',
'whisper "I am amazing" to yourself five times',
'write down nagging thoughts and throw them away',
'write down three totally random things you want to do someday'
    
]

module.exports = grains;
