let grains = [
{grainId: 1, category: 'surprise', text: `ask a friend or coworker what your strenghs and weaknesses are`},
{grainId: 2, category: 'surprise', text: `ask a random person what their favorite song is, play it, then jam out to it with them`},
{grainId: 3, category: 'surprise', text: `"ask someone who you kind of know what is their #1 hobby`},
{grainId: 4, category: 'surprise', text: `ask somone to move to Mexico with you, dont smile for a few seconds and see what they say`},
{grainId: 5, category: 'surprise', text: `call someone you love`},
{grainId: 6, category: 'surprise', text: `change your posture, try standing or sit up straight`},
{grainId: 7, category: 'surprise', text: `develop a cool secret handshake with the next person you see`},
{grainId: 8, category: 'surprise', text: `do 5 push ups`},
{grainId: 9, category: 'surprise', text: `do the hokey pokey and you turn yourself around`},
{grainId: 10, category: 'surprise', text: `do your best celebrity impersonation`},
{grainId: 11, category: 'surprise', text: `enjoy a walk in silence for a while`},
{grainId: 12, category: 'surprise', text: `finish all your sentences with "in accordance with the prophecy"`},
{grainId: 13, category: 'surprise', text: `give a warm hug to someone right now`},
{grainId: 14, category: 'surprise', text: `give every person you come in contact with a compliment today`},
{grainId: 15, category: 'surprise', text: `greet the next person you see in a different language`},
{grainId: 16, category: 'surprise', text: `laugh for no reason for 15 seconds`},
{grainId: 17, category: 'surprise', text: `lay down on the ground and say "I got this" really loudly`},
{grainId: 18, category: 'surprise', text: `learn a new word and use it five times today`},
{grainId: 19, category: 'surprise', text: `leave a dollar bill in a public place and see what happens`},
{grainId: 20, category: 'surprise', text: `lip sync for 30 seconds to a song your vibing with right now`},
{grainId: 21, category: 'surprise', text: `listen to a song in a different langauge`},
{grainId: 22, category: 'surprise', text: `maintain eye contact with a stranger`},
{grainId: 23, category: 'surprise', text: `only make left turns for 30 minutes, even while you walk`},
{grainId: 24, category: 'surprise', text: `part your hair on the opposite side or rub your head`},
{grainId: 25, category: 'surprise', text: `people watch for as long you can, see the beauty within every person who passes`},
{grainId: 26, category: 'surprise', text: `pick an accent different than your own and speak in it for 30 minutes`},
{grainId: 27, category: 'surprise', text: `press the button for a different floor in an elevator to where you work or where you are going, get off and meet people at a random  new company or service, tell them what you are up to`},
{grainId: 28, category: 'surprise', text: `put your watch on the opposite hand`},
{grainId: 29, category: 'surprise', text: `read the last page in a book nearby`},
{grainId: 30, category: 'surprise', text: `send a message to somone who you have not spoken to in a long time`},
{grainId: 31, category: 'surprise', text: `sit down on a bench and strike up a conversation with the first person who walks by`},
{grainId: 32, category: 'surprise', text: `skip instead of walk to your next destination`},
{grainId: 33, category: 'surprise', text: `spend a few minutes looking at your own eyes in the mirror`},
{grainId: 34, category: 'surprise', text: `spend five or ten minutes with yourself to reflect through prayer or meditation`},
{grainId: 35, category: 'surprise', text: `stand up and walk around during your calls today`},
{grainId: 36, category: 'surprise', text: `start break dancing the best you can for 30 seconds`},
{grainId: 37, category: 'surprise', text: `switch up placement of your rings or jewelry`},
{grainId: 38, category: 'surprise', text: `take a photo of your barefeet on the grass or ground`},
{grainId: 39, category: 'surprise', text: `take something apart and put it back together`},
{grainId: 40, category: 'surprise', text: `take the stairs`},
{grainId: 41, category: 'surprise', text: `text someone who you forgot to reply to recently`},
{grainId: 42, category: 'surprise', text: `walk backwards as long as you can without looking behind you`},
{grainId: 43, category: 'surprise', text: `walk up to someone and ask them if they can complete this phrase "in west philadelphia born and raised"`},
{grainId: 44, category: 'surprise', text: `when you withdraw money from the atm yell "i won i won! third time this week!"`},
{grainId: 45, category: 'surprise', text: `whisper "I am amazing" to yourself five times`},
{grainId: 46, category: 'surprise', text: `write down nagging thoughts and throw them away`},
{grainId: 47, category: 'surprise', text: `write down three totally random things you want to do someday`},
{grainId: 48, category: 'creativity', text: `Read this poem aloud in a mirror`},
{grainId: 49, category: 'creativity', text: `Share this art rendering with someone and ask how it makes them feel`},
{grainId: 50, category: 'creativity', text: `Learn a common phrase in a different language right now- dealers choice`},
{grainId: 51, category: 'creativity', text: `Research an era of history you didn't know about for the next few minutes`},
{grainId: 52, category: 'creativity', text: `Draw something with your eyes closed`},
{grainId: 53, category: 'creativity', text: `Be a sculptor- create something epic using random objects around you`},
{grainId: 54, category: 'creativity', text: `Doodle`},
{grainId: 55, category: 'creativity', text: `Spend 20 minutes working on a piece of mandala artwork`},
{grainId: 56, category: 'creativity', text: `Spend 15 minutes coloring today`},
{grainId: 57, category: 'creativity', text: `Design a tattoo for yourself...just the design:)`},
{grainId: 58, category: 'creativity', text: `Take a photo on your way to work, make it a great one`},
{grainId: 59, category: 'creativity', text: `Write your own poem out right now`},
{grainId: 60, category: 'creativity', text: `Write down things that made you laugh today`},
{grainId: 61, category: 'creativity', text: `Make a quote jar or folder`},
{grainId: 62, category: 'creativity', text: `Take something apart and put it back together`},
{grainId: 63, category: 'creativity', text: `Draw your best version of this picture`},
{grainId: 64, category: 'creativity', text: `Write a Haiku about your favorite childhood memory`},
{grainId: 65, category: 'creativity', text: `Close your eyes, circle your pointer on a menu. Order that item`},
{grainId: 66, category: 'education', text: `Read an article on a subject you know nothing about`},
{grainId: 67, category: 'education', text: `Show an interest in something new`},
{grainId: 68, category: 'education', text: `Learn something new from someone today`},
{grainId: 69, category: 'education', text: `Solve this IQ question`},
{grainId: 70, category: 'education', text: `Greek Gods and Godesses facts`},
{grainId: 71, category: 'education', text: `Solve this math problem`},
{grainId: 72, category: 'education', text: `Start a notebook of invention ideas`},
{grainId: 73, category: 'education', text: `Make a list of three topics you want to learn more about`},
{grainId: 74, category: 'education', text: `Research an idea/invention you've had to see if it exists`},
{grainId: 75, category: 'education', text: `If you taught a subject in school, what would it be and why?`},
{grainId: 76, category: 'education', text: `Take an online IQ test`},
{grainId: 77, category: 'education', text: `Pull out a book you've been meaning to read and put it on your nightstand`},
{grainId: 78, category: 'education', text: `Write a list of the top three brightest people you know. Call them and tell them you think so`},
{grainId: 79, category: 'home', text: `Create a jar for change`},
{grainId: 80, category: 'home', text: `Sell or give away an item today that you don't need, don't use or don't wear`},
{grainId: 81, category: 'home', text: `Reflect on your attitude towards money`},
{grainId: 82, category: 'home', text: `Google 'James Altucher and money'`},
{grainId: 83, category: 'home', text: `Leave a nice note or surprise for someone at home`},
{grainId: 84, category: 'home', text: `Don't eat a meal in front of the TV`},
{grainId: 85, category: 'home', text: `Make your bed today`},
{grainId: 86, category: 'home', text: `What's the one thing you would do everyday for free? Write down steps and ideas for accomplishing it`},
{grainId: 87, category: 'home', text: `Buy a plant and hang inspirational quotes from it`},
{grainId: 88, category: 'home', text: `Write out your three most important tasks today`},
{grainId: 89, category: 'home', text: `Check email only 2x today`},
{grainId: 90, category: 'home', text: `Come into work 30 mins early`},
{grainId: 91, category: 'home', text: `pour your milk first then cereal`},
{grainId: 92, category: 'home', text: `butter your toast with the opposite hand`},
{grainId: 93, category: 'home', text: `Press the button for a different floor in an elevator to where you work or where you're going. Get off and meet people at a random new company or service. Tell them what you're up to!`},
{grainId: 94, category: 'home', text: `Rearrange your cupboards at home`},
{grainId: 95, category: 'home', text: `Send an email to yourself about why you love your job. Read it tomorrow`},
{grainId: 96, category: 'home', text: `Call your boss, "boss."`},
{grainId: 97, category: 'home', text: `Sleep with your head at the opposite end of the bed`},
{grainId: 98, category: 'home', text: `Write down where you would like to be financially in 5 years`},
{grainId: 99, category: 'home', text: `Make and eat a sandhich with the inside on the outside`},    
{grainId: 100, category: 'inner', text: `Spend 5 minutes aware of your breath`},
{grainId: 101, category: 'inner', text: `Research mantras and develop your own right now!`},
{grainId: 102, category: 'inner', text: `Don't look in the mirror today`},
{grainId: 103, category: 'inner', text: `Spend five minutes looking into your own eyes in the mirror`},
{grainId: 104, category: 'inner', text: `Go make up free today`},
{grainId: 105, category: 'inner', text: `Gently massage under your eyes`},
{grainId: 106, category: 'inner', text: `Floss`},
{grainId: 107, category: 'inner', text: `Discover your Ayurvedic Dosha type`},
{grainId: 108, category: 'inner', text: `Mindfully prepare and drink a cup of tea`},
{grainId: 109, category: 'inner', text: `Start a image/vision board`},
{grainId: 110, category: 'inner', text: `Write yourself a cheque for a certain amount`},
{grainId: 111, category: 'inner', text: `Who are you`},
{grainId: 112, category: 'inner', text: `Which fictional character would you be and why?`},
{grainId: 113, category: 'inner', text: `Do you believe in god or a higher power? If so, why/why not?`},
{grainId: 114, category: 'inner', text: `Enter a place of worship, different than what you believe`},
{grainId: 115, category: 'inner', text: `Write a Haiku about what you are doing in the present moment`},
{grainId: 116, category: 'inner', text: `Write a letter to your future self`},
{grainId: 117, category: 'inner', text: `Write a letter to your unborn child`},
{grainId: 118, category: 'inner', text: `Do a five minute body scan`},
{grainId: 119, category: 'inner', text: `Drive in silience`},
{grainId: 120, category: 'inner', text: `Tense your musles for 10 seconds. Relax for 10. Repeat 10 times`},
{grainId: 121, category: 'inner', text: `Notice and feel the weather on your skin`},
{grainId: 122, category: 'relationships', text: `Give up your seat the next time you see an oppty`},
{grainId: 123, category: 'relationships', text: `Give a compliment to the next person you see`},
{grainId: 124, category: 'relationships', text: `Write a nice/funny horoscope for yourself`},
{grainId: 125, category: 'relationships', text: `Don't check your phone when you're with someone else`},
{grainId: 126, category: 'relationships', text: `Pick an animal at random and try to imitate the noise you think they make`},
{grainId: 127, category: 'relationships', text: `Ask someone to do their best 'whip noise'`},
{grainId: 128, category: 'relationships', text: `Learn a go to joke and perfect telling it`},
{grainId: 129, category: 'relationships', text: `Play one good song today and enjoy it!`},
{grainId: 130, category: 'relationships', text: `Design a treasure hunt for someone else`},
{grainId: 131, category: 'relationships', text: `speak to someone new today`},
{grainId: 132, category: 'relationships', text: `strike up a conversation with a stranger while you're waiting for something today`},
{grainId: 133, category: 'relationships', text: `Hold eye contact with a stranger for longer than 5 seconds`},
{grainId: 134, category: 'relationships', text: `Befriend someone on the bus or train`},
{grainId: 135, category: 'relationships', text: `Talk less. Listen more`},
{grainId: 136, category: 'relationships', text: `Talk more`},
{grainId: 137, category: 'relationships', text: `"Ask someone who you kind of know what's their #1 hobby`},
{grainId: 138, category: 'relationships', text: `greet people today in a different language`},
{grainId: 139, category: 'relationships', text: `Send a message to somone who you haven't spoken to in over a year`},
{grainId: 140, category: 'relationships', text: `Don't shake hands for a day, bow appropriately (video link coming)`},
{grainId: 141, category: 'relationships', text: `Make a toast to the table next to you while out to dinner`},
{grainId: 142, category: 'relationships', text: `Smell your partner for 5 full minutes`},
{grainId: 143, category: 'relationships', text: `Say yes to the next three things you are asked`},
{grainId: 144, category: 'relationships', text: `Write a list of the top three nicest people you know. Call them and tell them you think so`},
{grainId: 145, category: 'relationships', text: `Thank a stranger for their smile`},
{grainId: 146, category: 'relationships', text: `Buy an appetizer for the table next to you at dinner`},
{grainId: 147, category: 'relationships', text: `Give a note to a stranger reading, "today is going to be a good day."`},
{grainId: 148, category: 'home', text: `Research a good money management app`},
{grainId: 149, category: 'physical', text:`Take a cold shower`},
{grainId: 150, category: 'physical', text:`Steam your face`},
{grainId: 151, category: 'physical', text:`Eat 5 pieces of fruit and veg today`},
{grainId: 152, category: 'physical', text:`Don't drink caffeine after midday...ahhhh`},
{grainId: 153, category: 'physical', text:`Try eating at different times than you're used to today`},
{grainId: 154, category: 'physical', text:`Dance right now even if people are watching!`},
{grainId: 155, category: 'physical', text:`Try to do a handstand`},
{grainId: 156, category: 'physical', text:`Balance something on your head`},
{grainId: 157, category: 'physical', text:`Think only good thoughts before going to bed`},
{grainId: 158, category: 'physical', text:`place something good smelling under your pillow`},
{grainId: 159, category: 'physical', text:`read something that makes you feel good before sleep`},
{grainId: 160, category: 'physical', text:`Order a non alcoholic drink of your favorite drink`},
{grainId: 161, category: 'physical', text:`Get a manicure or pedicure; you too guys`},
{grainId: 162, category: 'physical', text:`Sleep with your head at the foot of the bed`},
{grainId: 163, category: 'physical', text:`Stop and do 5 push ups`},
{grainId: 164, category: 'physical', text:`Men; get a shave at a professional barber`},
{grainId: 165, category: 'physical', text:`take the stairs`},
{grainId: 166, category: 'physical', text:`Change your posture. Stand or Sit up Straight`},
{grainId: 167, category: 'physical', text:`Let the person next to you pick your next manicure color`},
{grainId: 168, category: 'physical', text:`Put your eating utensil down in between each bite`},
{grainId: 169, category: 'physical', text:`Go to bed one hour earlier`},
{grainId: 170, category: 'physical', text:`Write a list of your three best physical assets`},
{grainId: 171, category: 'physical', text:`Buy a vegetable you dont typcially eat at the market`},
]

module.exports = grains;
