'use strict'
const React = require('react-native');
const { StyleSheet, Dimensions } = React;

module.exports = StyleSheet.create({
  surpriseCategoryHeading:{
    fontSize: 20,
    textAlign: 'center',
  },
  surpriseGrainCategory: {
    borderRadius: 10,
    flex: 2,
    flexDirection: 'row',
    margin: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgb(123, 129, 137)',
    backgroundColor: 'rgba(255,255,255,0)',
    marginLeft: '10%',
    marginRight: '10%',
    marginTop: '-10%',
  },
  notifications: {
    borderRadius: 10,
    flex: 2,
    flexDirection: 'row',
    margin: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgb(123, 129, 137)',
    backgroundColor: 'rgba(255,255,255,0)',
    marginLeft: '10%',
    marginRight: '10%',
    marginTop: 10,
  },
  footer: {
    flex: 1,
    flexDirection: 'row',
    margin: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0)',
  },
  header: {
    flex: 1,
    flexDirection: 'row',
    margin: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0)',
  },
  allCategoriesHeadingView:{
    borderRadius: 10,
    flex: 1,
    flexDirection: 'row',
    margin: 10,
    justifyContent: 'center',
    alignItems: 'center',
    height: '7.5%',
    width: '100%',
    backgroundColor: 'rgba(0,0,0,0)',
  },
  allCategoriesHeading:{
    fontSize: 20,
    textAlign: 'center',
  },
  categoryHeading:{
    fontSize: 20,
    textAlign: 'center',
  },
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover', // or 'stretch',
    width: null,
    height: null,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    // alignItems: 'center',
  },
  grainCategory: {
    borderRadius: 10,
    flex: 1,
    flexDirection: 'row',
    margin: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgb(123, 129, 137)',
    backgroundColor: 'rgba(255,255,255,0)',
    padding: 2,
  },
  categoriesContainerRow: {
    backgroundColor: 'rgba(0,0,0,0)',
    flexDirection: 'row',
    height: '25%',
    width: '80%',
    flexWrap: 'wrap',
    marginTop: 2,
  },
  allGrainCategories: {
    width: Dimensions.get('window').width,
    backgroundColor: 'rgba(0,0,0,0)',
    flex: 10,
    flexDirection: 'column',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center'
  },
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },

});